# Generated by Django 6.1.1 on 2026-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelapplication',
            name='label_sample_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
